### PR TITLE
154 idorder is not stored with the table

### LINKED ISSUE #154: idOrder is not stored with the table
**Describe the bug**
The idOrder stored in the pos_config is not stored in the table local storage on the client.

**Expected behavior**
The table object should also contains the orderId, to be used to recall the order when recalling the linked order.

### PR DESCRIPTION
**Pull request by Lucaslgd02**
## Describe your changes
Add orderId to tables
## How to test the feature
Select a table
Make an order and submit it
The orderId is now linked to the corresponding table
## Issue ticket number and link
Closes #154 
## Checklist before requesting a review
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Documentation has been updated as required
If a single item in this checklist is not checked, the pull request cannot be accepted

### CODE REVIEW

**Comment by Lucaslgd02** [comment]
Requires Back-End PR 151 to be accepted beforehand

**Comment by JulesGresset** [comment]
This is not what the issue is about.
The orderId is already send by the backend to the POS with the ``/pos_config`` route called on the loading page where the data about the table is stored in the local storage, but not the orderId.
The issue is about adding the orderId in the local storage on loading.

File: src/Components/CurrentCommand/CurrentCommand.js [hunk 1]
```diff
@@ -317,6 +317,22 @@ function Footer({ config, orders, setOrders, setConfig, price, priceLess, payLis
...
+                      },
+                    }
+                  )
+                  .then((response) => {
+                    if (response.status === 401) {
+                      throw new Error("Unauthorized access. Please log in.");
+                    }
+                    return response.json();
+                  })
+            })
```
Comment (JulesGresset) [inline src/Components/CurrentCommand/CurrentCommand.js:335]: This part should be removed.
The pos_config will automaticaly update when the "TABLES" tab is selected.

**Review by JulesGresset — CHANGES_REQUESTED** [review]
Feature works as intended, just a small modification needed to avoid multiple call to the back-end.

**Review by JulesGresset — APPROVED** [review]
